#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

# General App Info
app:
  name: REAL items - Digital Receipts of Authenticity # REQUIRED - Enter your app name
  ios_id:  # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: 
  apk_link: 
  icon: images/app-icon-512.png

# Permalinks
permalink: /:title

# Marketing
marketing_header: # Optional
marketing_desc: Trust - Secure wallet for Digital Receipts, Authentic items and AI22 tokens.

# Social Links
social-links:
  github: AGENC1
  discord: 
  reddit: 
  medium: 
  youtube: 
  twitter: AGENC1
  facebook: AGENC1
  email: info@AGENC1.io


# Enable/Disable Features & Page Elements
enable:
  app_icon: true
  smart_app_banner: true

# Theme Settings
background_color: "#2e91db" # Optional
background_image: # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

# Site Info - specific meta
title: REAL items - Digital Receipts of Authenticity
description: REAL items - Secure wallet for Digital Receipts, Authentic Items and AI22 tokens.

# Google Analytics
google_analytics:  # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - vendor

# Build settings
markdown: kramdown
